services:
  postgres:
    container_name: department-database-container
    image: postgres:18
    environment:
      POSTGRES_DB: department-db
      POSTGRES_USER: canioves
      POSTGRES_PASSWORD: c23315Ht5
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres
    
volumes:
  postgresdb-data:

networks:
  postgres:
    driver: bridge